FROM node:18 AS express
WORKDIR /app
COPY ./backend/package.json ./backend/package-lock.json .
RUN npm install --include=dev
COPY ./backend .
EXPOSE 5000
CMD ["npx", "nodemon", "src/index.js"]

FROM node:18 AS vite
WORKDIR /app
COPY /frontend/package.json /frontend/package-lock.json .
RUN npm install
COPY ./frontend .
EXPOSE 5173
CMD ["npm", "run", "dev"]

FROM express AS websocket
WORKDIR /app
COPY /backend/package.json /backend/package-lock.json .
RUN npm install --include=dev
COPY ./backend .
EXPOSE 5001
CMD ["npx", "nodemon", "src/ws/index.js"]

FROM nginx:alpine AS nginx
WORKDIR usr/share/nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
