FROM node:18 AS express
WORKDIR /app
COPY ./backend/package.json ./backend/package-lock.json .
RUN npm install
COPY ./backend .
EXPOSE 5000
CMD ["npm", "run", "dev"]

FROM node:18 AS vite
WORKDIR /app
COPY /frontend/package.json /frontend/package-lock.json .
RUN npm install
COPY ./frontend .
EXPOSE 5173
CMD ["npm", "run", "dev"]

FROM nginx:alpine AS nginx
WORKDIR usr/share/nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
